language: php

sudo: false

addons:
  apt:
    packages:
      - tidy

env:
  global:
    - TRAVIS_NODE_VERSION="6"
    - COMPOSER_ROOT_VERSION=1.0.x-dev
    - DISPLAY=":99"
    - XVFBARGS=":99 -ac -screen 0 1024x768x16"

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: DB=PGSQL PHPUNIT_TEST=1
    - php: 5.6
      env: DB=MYSQL PHPUNIT_TEST=1 PHPCS_TEST=1
    - php: 7.0
      env: DB=MYSQL PHPUNIT_TEST=1
    - php: 7.1
      env: DB=MYSQL PDO=1
    - php: 5.6
      env: NPM_TEST=1

before_script:
  - export CORE_RELEASE=$TRAVIS_BRANCH
  - printf "\n" | pecl install imagick
  - if [[ $PHPCS_TEST ]]; then pyrus install pear/PHP_CodeSniffer; fi
  - phpenv rehash
  - phpenv config-rm xdebug.ini
  - composer validate
  - composer install --prefer-dist
  - composer require --prefer-dist --no-update symfony/config:^3.2 silverstripe/framework:4.0.x-dev embed/embed:^3.0@stable silverstripe/config:1.0.x-dev silverstripe/versioned:1.0.x-dev silverstripe/assets:1.0.x-dev silverstripe/admin:1.0.x-dev
  - composer update
  - if [[ $DB == PGSQL ]]; then composer require silverstripe/postgresql:2.0.x-dev --prefer-dist; fi
  - if [[ $DB == SQLITE ]]; then composer require silverstripe/sqlite3:2.0.x-dev --prefer-dist; fi
  - if [[ $NPM_TEST ]]; then nvm install $TRAVIS_NODE_VERSION && npm install -g yarn && yarn install --network-concurrency 1 && yarn run build; fi

script:
  - if [[ $PHPUNIT_TEST ]]; then vendor/bin/phpunit tests/php; fi
  - if [[ $NPM_TEST ]]; then git diff-files --quiet -w --relative=client; fi
  - if [[ $NPM_TEST ]]; then git diff --name-status --relative=client; fi
  - if [[ $NPM_TEST ]]; then yarn run lint; fi
  - if [[ $PHPCS_TEST ]]; then composer run-script lint; fi
